### PR TITLE
Chore: Drop gorilla and go-chi from main go.mod

### PR DESCRIPTION
**Pull request by akojo**
To avoid bringing along unnecessary dependencies:
- Add go.mod to examples to keep them from polluting main go.mod
- Use http.ServeMux as handler in test
- Create separate testdata directory with a plain net/http server for
  test docs

### CODE REVIEW

**Review by Am3o — APPROVED** [review]
Good job!

**Comment by fr3fou** [comment]
Will this get merged?

**Comment by ubogdan** [comment]
> Will this get merged?

Yes.

**Comment by akojo** [comment]
> @akojo can you please fix the conflict and let me know so I can merge this.

Done

**Pull request merged**
